<?php
 /**
 * 
 *
 * The template for user side bar with user details.
 *
 
 * Please do not edit this file. This file is part of the custom code Framework and all modifications

 */

$profile_id = um_profile_id();

$mobile_number=get_user_meta( $profile_id, 'mobile_number', 'true'); 
$user_info = get_userdata($profile_id);
// userProfile url
$user_image=get_avatar_url( $profile_id );
// display name
$first_name=get_user_meta( $profile_id, 'first_name', 'true'); 
$last_name=get_user_meta( $profile_id, 'last_name', 'true'); 
$displayName='';
if($first_name){
  $displayName=$first_name ." ".$last_name;
}else{
  $displayName=$user_info->user_email;
}
//socail key word
$facebook=get_user_meta( $profile_id, 'facebook', 'true'); 
$twitter=get_user_meta( $profile_id, 'twitter', 'true'); 
$instagram=get_user_meta( $profile_id, 'instagram', 'true'); 
$googleplus=get_user_meta( $profile_id, 'googleplus', 'true'); 
$country=get_user_meta( $profile_id, 'country', 'true'); 
$where_i_live =  get_user_meta( $profile_id, 'user-citys', 'true');
$stadium_position =  get_user_meta( $profile_id, 'stadium-position', 'true');

$passions_position =  get_user_meta( $profile_id, 'passions', 'true');
$team_name=   get_user_meta( $profile_id, 'team-names', 'true');
$user = get_userdata( um_profile_id());
$user_roles = $user->roles;
$roleis='';
  if ( in_array( 'customer', $user_roles, true ) ) {
     $roleis='customer';
}
 


// for langugas
$languages=get_user_meta( $profile_id, 'languages', 'true'); 
 $isoLangs = [
    "ab"=>"Abkhaz",
    "aa"=>"Afar",
    "af"=>"Afrikaans",
    "ak"=>"Akan",
    "sq"=>"Albanian",
    "am"=>"Amharic",
    "ar"=>"Arabic",
    "an"=>"Aragonese",
    "hy"=>"Armenian",
    "as"=>"Assamese",
    "av"=>"Avaric",
    "ae"=>"Avestan",
    "ay"=>"Aymara",
    "az"=>"Azerbaijani",
    "bm"=>"Bambara",
    "ba"=>"Bashkir",
    "eu"=>"Basque",
    "be"=>"Belarusian",
    "bn"=>"Bengali",
    "bh"=>"Bihari",
    "bi"=>"Bislama",
    "bs"=>"Bosnian",
    "br"=>"Breton",
    "bg"=>"Bulgarian",
    "my"=>"Burmese",
    "ca"=>"Catalan Valencian",
    "ch"=>"Chamorro",
    "ce"=>"Chechen",
    "ny"=>"Chichewa Chewa Nyanja",
    "zh"=>"Chinese",
    "cv"=>"Chuvash",
    "kw"=>"Cornish",
    "co"=>"Corsican",
    "cr"=>"Cree",
    "hr"=>"Croatian",
    "cs"=>"Czech",
    "da"=>"Danish",
    "dv"=>"Divehi Dhivehi Maldivian",
    "nl"=>"Dutch",
    "en"=>"English",
    "eo"=>"Esperanto",
    "et"=>"Estonian",
    "ee"=>"Ewe",
    "fo"=>"Faroese",
    "fj"=>"Fijian",
    "fi"=>"Finnish",
    "fr"=>"French",
    "ff"=>"Fula Fulah Pulaar Pular",
    "gl"=>"Galician",
    "ka"=>"Georgian",
    "de"=>"German",
    "el"=>"Greek, Modern",
    "gn"=>"Guaraní",
    "gu"=>"Gujarati" ,
    "ht"=>"Haitian Haitian Creole",
    "ha"=>"Hausa",
    "he"=>"Hebrew",
    "hz"=>"Herero",
    "hi"=>"Hindi",
    "ho"=>"Hiri Motu",
    "hu"=>"Hungarian",
    "ia"=>"Interlingua",
    "id"=>"Indonesian",
    "ie"=>"Interlingue",
    "ga"=>"Irish",
    "ig"=>"Igbo",
    "ik"=>"Inupiaq",
    "io"=>"Ido",
    "is"=>"Icelandic",
    "it"=>"Italian",
    "iu"=>"Inuktitut",
    "ja"=>"Japanese",
    "jv"=>"Javanese",
    "kl"=>"Kalaallisut Greenlandic",
    "kn"=>"Kannada",
    "kr"=>"Kanuri",
    "ks"=>"Kashmiri",
    "kk"=>"Kazakh",
    "km"=>"Khmer",
    "ki"=>"Kikuyu Gikuyu",
    "rw"=>"Kinyarwanda",
    "ky"=>"Kirghiz, Kyrgyz",
    "kv"=>"Komi",
    "kg"=>"Kongo",
    "ko"=>"Korean",
    "ku"=>"Kurdish",
    "kj"=>"Kwanyama, Kuanyama",
    "la"=>"Latin",
    "lb"=>"Luxembourgish, Letzeburgesch",
    "lg"=>"Luganda",
    "li"=>"Limburgish, Limburgan, Limburger",
    "ln"=>"Lingala",
    "lo"=>"Lao",
    "lt"=>"Lithuanian",
    "lu"=>"Luba-Katanga",
    "lv"=>"Latvian",
    "gv"=>"Manx",
    "mk"=>"Macedonian",
    "mg"=>"Malagasy",
    "ms"=>"Malay",
    "ml"=>"Malayalam",
    "mt"=>"Maltese",
    "mi"=>"Māori",
    "mr"=>"Marathi (Marāṭhī)",
    "mh"=>"Marshallese",
    "mn"=>"Mongolian",
    "na"=>"Nauru",
    "nv"=>"Navajo, Navaho",
    "nb"=>"Norwegian Bokmål",
    "nd"=>"North Ndebele",
    "ne"=>"Nepali",
    "ng"=>"Ndonga",
    "nn"=>"Norwegian Nynorsk",
    "no"=>"Norwegian",
    "ii"=>"Nuosu",
    "nr"=>"South Ndebele",
    "oc"=>"Occitan",
    "oj"=>"Ojibwe, Ojibwa",
    "cu"=>"Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic",
    "om"=>"Oromo",
    "or"=>"Oriya",
    "os"=>"Ossetian, Ossetic",
    "pa"=>"Panjabi, Punjabi",
    "pi"=>"Pāli",
    "fa"=>"Persian",
    "pl"=>"Polish",
    "ps"=>"Pashto, Pushto",
    "pt"=>"Portuguese",
    "qu"=>"Quechua",
    "rm"=>"Romansh",
    "rn"=>"Kirundi",
    "ro"=>"Romanian, Moldavian, Moldovan",
    "ru"=>"Russian",
    "sa"=>"Sanskrit (Saṁskṛta)",
    "sc"=>"Sardinian",
    "sd"=>"Sindhi",
    "se"=>"Northern Sami",
    "sm"=>"Samoan",
    "sg"=>"Sango",
    "sr"=>"Serbian",
    "gd"=>"Scottish Gaelic; Gaelic",
    "sn"=>"Shona",
    "si"=>"Sinhala, Sinhalese",
    "sk"=>"Slovak",
    "sl"=>"Slovene",
    "so"=>"Somali",
    "st"=>"Southern Sotho",
    "es"=>"Spanish; Castilian",
    "su"=>"Sundanese",
    "sw"=>"Swahili",
    "ss"=>"Swati",
    "sv"=>"Swedish",
    "ta"=>"Tamil",
    "te"=>"Telugu",
    "tg"=>"Tajik",
    "th"=>"Thai",
    "ti"=>"Tigrinya",
    "bo"=>"Tibetan Standard, Tibetan, Central",
    "tk"=>"Turkmen",
    "tl"=>"Tagalog",
    "tn"=>"Tswana",
    "to"=>"Tonga (Tonga Islands)",
    "tr"=>"Turkish",
    "ts"=>"Tsonga",
    "tt"=>"Tatar",
    "tw"=>"Twi",
    "ty"=>"Tahitian",
    "ug"=>"Uighur, Uyghur",
    "uk"=>"Ukrainian",
    "ur"=>"Urdu",
    "uz"=>"Uzbek",
    "ve"=>"Venda",
    "vi"=>"Vietnamese",
    "vo"=>"Volapük",
    "wa"=>"Walloon",
    "cy"=>"Welsh",
    "wo"=>"Wolof",
    "fy"=>"Western Frisian",
    "xh"=>"Xhosa",
    "yi"=>"Yiddish",
    "yo"=>"Yoruba",
    "za"=>"Zhuang, Chuang"
];
$countryCode= [
"af"=>"ZA",
"am"=>"ET",
"ar"=>"AE",
"ar"=>"BH",
"ar"=>"DZ",
"ar"=>"EG",
"ar"=>"IQ",
"ar"=>"JO",
"ar"=>"KW",
"ar"=>"LB",
"ar"=>"LY",
"ar"=>"MA",
"arn"=>"CL",
"ar"=>"OM",
"ar"=>"QA",
"ar"=>"SA",
"ar"=>"SY",
"ar"=>"TN",
"ar"=>"YE",
"as"=>"IN",
"az"=>"Cyr",
"l"=>"AZ",
"az"=>"Latn",
"ba"=>"RU",
"be"=>"BY",
"bg"=>"BG",
"bn"=>"BD",
"bn"=>"IN",
"bo"=>"CN",
"br"=>"FR",
"bs"=>"Cyr",
"l"=>"BA",
"bs"=>"Latn",
"ca"=>"ES",
"co"=>"FR",
"cs"=>"CZ",
"cy"=>"GB",
"da"=>"DK",
"de"=>"AT",
"de"=>"CH",
"de"=>"DE",
"de"=>"LI",
"de"=>"LU",
"dsb"=>"DE",
"dv"=>"MV",
"el"=>"GR",
"en"=>"029",
"en"=>"AU",
"en"=>"BZ",
"en"=>"CA",
"en"=>"GB",
"en"=>"IE",
"en"=>"IN",
"en"=>"JM",
"en"=>"MY",
"en"=>"NZ",
"en"=>"PH",
"en"=>"SG",
"en"=>"TT",
"en"=>"US",
"en"=>"ZA",
"en"=>"ZW",
"es"=>"AR",
"es"=>"BO",
"es"=>"CL",
"es"=>"CO",
"es"=>"CR",
"es"=>"DO",
"es"=>"EC",
"es"=>"ES",
"es"=>"GT",
"es"=>"HN",
"es"=>"MX",
"es"=>"NI",
"es"=>"PA",
"es"=>"PE",
"es"=>"PR",
"es"=>"PY",
"es"=>"SV",
"es"=>"US",
"es"=>"UY",
"es"=>"VE",
"et"=>"EE",
"eu"=>"ES",
"fa"=>"IR",
"fi"=>"FI",
"fil"=>"PH",
"fo"=>"FO",
"fr"=>"BE",
"fr"=>"CA",
"fr"=>"CH",
"fr"=>"FR",
"fr"=>"LU",
"fr"=>"MC",
"fy"=>"NL",
"ga"=>"IE",
"gd"=>"GB",
"gl"=>"ES",
"gsw"=>"FR",
"gu"=>"IN",
"ha"=>"Lat",
"n"=>"NG",
"he"=>"IL",
"hi"=>"IN",
"hr"=>"BA",
"hr"=>"HR",
"hsb"=>"DE",
"hu"=>"HU",
"hy"=>"AM",
"id"=>"ID",
"ig"=>"NG",
"ii"=>"CN",
"is"=>"IS",
"it"=>"CH",
"it"=>"IT",
"iu"=>"Can",
"s"=>"CA",
"iu"=>"Latn",
"ja"=>"JP",
"ka"=>"GE",
"kk"=>"KZ",
"kl"=>"GL",
"km"=>"KH",
"kn"=>"IN",
"kok"=>"IN",
"ko"=>"KR",
"ky"=>"KG",
"lb"=>"LU",
"lo"=>"LA",
"lt"=>"LT",
"lv"=>"LV",
"mi"=>"NZ",
"mk"=>"MK",
"ml"=>"IN",
"mn"=>"MN",
"mn"=>"Mon",
"g"=>"CN",
"moh"=>"CA",
"mr"=>"IN",
"ms"=>"BN",
"ms"=>"MY",
"mt"=>"MT",
"nb"=>"NO",
"ne"=>"NP",
"nl"=>"BE",
"nl"=>"NL",
"nn"=>"NO",
"nso"=>"ZA",
"oc"=>"FR",
"or"=>"IN",
"pa"=>"IN",
"pl"=>"PL",
"prs"=>"AF",
"ps"=>"AF",
"pt"=>"BR",
"pt"=>"PT",
"qut"=>"GT",
"quz"=>"BO",
"quz"=>"EC",
"quz"=>"PE",
"rm"=>"CH",
"ro"=>"RO",
"ru"=>"RU",
"rw"=>"RW",
"sah"=>"RU",
"sa"=>"IN",
"se"=>"FI",
"se"=>"NO",
"se"=>"SE",
"si"=>"LK",
"sk"=>"SK",
"sl"=>"SI",
"sma"=>"NO",
"sma"=>"SE",
"smj"=>"NO",
"smj"=>"SE",
"smn"=>"FI",
"sms"=>"FI",
"sq"=>"AL",
"sr"=>"Cyr",
"l"=>"B",
"sr"=>"Cyrl",
"sr"=>"Cyrl",
"sr"=>"Cyrl",
"sr"=>"Latn",
"sr"=>"Latn=>CS",
"sr"=>"Latn=>ME",
"sr"=>"Latn=>RS",
"sv"=>"FI",
"sv"=>"SE",
"sw"=>"KE",
"syr"=>"SY",
"ta"=>"IN",
"te"=>"IN",
"tg"=>"Cyr",
"l"=>"TJ",
"th"=>"TH",
"tk"=>"TM",
"tn"=>"ZA",
"tr"=>"TR",
"tt"=>"RU",
"tzm"=>"La",
"tn"=>"DZ",
"ug"=>"CN",
"uk"=>"UA",
"ur"=>"PK",
"uz"=>"Cyr",
"uz"=>"Latn",
"vi"=>"VN",
"wo"=>"SN",
"xh"=>"ZA",
"yo"=>"NG",
"zh"=>"CN",
"zh"=>"HK",
"zh"=>"MO",
"zh"=>"SG",
"zh"=>"TW",
"zu"=>"ZA",
"en"=>"US",
];


  
?>

<div class="side-container boot-col-md-3 ">
   <div class="user-container um-theme-profile-single-content-container">
   	  <div class="user-profile boot-col-md-12">
   	  	 <div class="user-profile-group center">
            <!-- <div class="contact-phone">
               <a href="tel:<?php echo $mobile_number; ?>">
                   <i class="fa fa-phone  fa-rotate-90 rounded-icon"></i>  
                </a>
            </div> -->
            <div class="image">
               <img src="<?php echo $user_image; ?>" class="avarar_image">
               <!-- <span class="online-us">
                <span id="user_status_online-offline"></span>
                <?php // do_action( 'um_after_profile_name_inline', $args ); ?>
               </span> -->
             </div> 
             <!-- <div class="contact-mail">
                
              <a href="mailto:<?php echo $user_info->user_email; ?>">
               <i class="fa fa-envelope rounded-icon"></i></a>
             </div>  -->
          </div>
   	  	 <div class="details">
   	  	 	<p class="um-display-name"><?php echo ucfirst($displayName); ?>
           
          </p>
          <?php 
            if(get_current_user_id()==$profile_id ){
             
               ?>
			   
                <a href="?um_action=edit" class="edit-profile-btn">
                <?php 
                if ($_GET['um_action']=='edit') {
                ?>
                  <span title="<?php the_field('about_toll_tip', 'option'); ?>"class="tooltip" >?</span>
                <?php }?>

				Edit Profile</a>
				<?php
			   
            } 
          ?>
          <?php echo do_shortcode('[ultimatemember_message_button user_id="'.$profile_id.'" ]');?>
   	  	 </div>
           <?php  $rating = UM()->Reviews_API()->api()->get_rating( $profile_id ); ?>
   	  	 <div class="rating">
   	  	 	<ul class="rating-ul">
               <?php $totalReview=5;
                     $blankREview=$totalReview-$rating;
                     for($i=1 ; $i<=$rating ; $i++){
                        echo '<li><i class="star-on-png"></i></li>';
                     }
                     for($i=1 ; $i<=$blankREview ; $i++){
                        echo '<li><i class="star-off-png"></i></li>';
                     }
               ?>

   	  	 	</ul>
   	  	 	<p>Rating <?php echo $rating; ?> - 5</p>
          </div>
   	  	 <!-- <div class="social-deatails">
   	  	 	<ul class="socail-ul">
   	  	 		<?php
                  if($facebook){
                  	echo '<li><a href="'.$facebook.'"><i class="um-faicon-facebook"></i></a></li>';
                  }
                  if($twitter){
                  	echo '<li><a href="'.$twitter.'"><i class="um-faicon-twitter"></i></a></li>';
                  }
                  if($instagram){
                  	echo '<li><a href="'.$instagram.'"><i class="um-faicon-instagram"></i></a></li>';
                  }
                  if($googleplus){
                  	echo '<li><a href="https://google.com/'.$googleplus.'"><i class="um-faicon-google-plus"></i></a></li>';
                  }
   	  	 		 ?>
   	  	 		
   	  	 	</ul>
   	  	 </div> -->
   	  </div>
      <?php  if($roleis !='customer'){ ?>
      <div class="team-section">
          <h6>Team</h6>
          
          <p>
             <span>
                <?php echo $team_name; ?>
             </span>
          </p>
      </div>
      <div class="stadium-section">
          <h6>Where I live</h6>
          <ul class="location-details">
            <li><i class="fa fa-users color-second"></i>City : <span><?php echo $where_i_live ?></span></li>
             <li><i class="fa fa-birthday-cake color-third"></i>Country : <span><?php echo $country; ?></span></li>

          </ul>
 
      </div>
      <div class="language-section">
          <h6>Spoken Languages</h6>
          <ul class="location-details">
             <?php
                   foreach ($languages as $key => $value) {
                     foreach ($isoLangs as $key2 => $value2) {
                        if($value2==$value){
                          foreach ($countryCode as $key3 => $value3) {
                             if($key3==$key2){
                              ?>
                          <li>
                           <p><img src="https://www.geonames.org/flags/x/<?php echo strtolower($value3); ?>.gif" class="flag-image">
                             <span class="te-right"><?php echo $value; ?></span>
                          </p>
                           </li>
                          <?php
                             }
                          }
                          
                        }
                     }
                      
                   }
              ?>
          </ul>
      </div>
      <div class="language-section" id="passion-list">
          <h6>Passions</h6>
          <ul class="passions-details">
            <?php
            for( $ps = 1; $ps <= 10; $ps++){
                $passions_val = trim(get_user_meta( $profile_id, 'passion-'.$ps, true));
                if( '' != $passions_val ){
                    echo "<li>". $passions_val ."</li>";
                }
            }
              
            ?>
          </ul>
      </div>
    <?php } ?>
      
   </div>

</div>